[package]
name = "fraudguard"
edition = "2024.beta"
license = "MIT"
authors = ["FraudGuard Team"]

[dependencies]
# Sui framework dependencies are automatically included

[addresses]
fraudguard = "0x0"

[dev-dependencies]
# The dev-dependencies section allows overriding dependencies for `--test` and
# `--dev` modes. You can introduce test-only dependencies here.

[dev-addresses]
# The dev-addresses section allows overwriting named addresses for the `--test`
# and `--dev` modes.